Consolidate long-press menu for article items
wikimedia/apps-android-wikipedia pull request #1835
Opened 2020-12-02 01:16 UTC by cooltey

https://phabricator.wikimedia.org/T268723

2021-01-07 15:44 UTC, dbrant requested changes

2021-01-08 00:51 UTC, cooltey commented on app/src/main/res/values-qq/strings.xml
> +  <string name="article_opened_in_background_tab">Message that notifies the user that the article has been opened in a background.</string>
You are correct. Done.

2021-01-08 00:51 UTC, cooltey commented on app/src/main/res/values/strings.xml
> +    <string name="article_opened_in_background_tab">Your article has been opened in background.</string>
You are correct. Done.

2021-01-08 00:51 UTC, cooltey commented on app/src/main/java/org/wikipedia/util/TabUtil.kt
> +        app.commitTabState()
Done.

2021-01-12 14:18 UTC, merged