Kotlin conversion: AnimationUtil, ActiveTimer and ArrayUtils converted
wikimedia/apps-android-wikipedia pull request #1950
Opened 2021-01-21 21:53 UTC by sharvaniharan

2021-01-21 22:55 UTC, cooltey requested changes

2021-01-21 22:55 UTC, cooltey commented on app/src/main/java/org/wikipedia/util/ArrayUtils.kt
> +        return ArrayUtils.removeAll(array, *Arrays.copyOf(indices, count))
The `copyOf` can be simplified.

2021-01-21 22:55 UTC, cooltey commented on app/src/main/java/org/wikipedia/util/ArrayUtils.kt
> +// https://rink.hockeyapp.net/manage/apps/226650/app_versions/79/crash_reasons/156658637
The URL is invalid. Can we update or remove the comment?

2021-01-21 22:55 UTC, cooltey commented on app/src/main/java/org/wikipedia/util/ActiveTimer.kt
> +    }
Would it be possible to move `init{}` to the top of these methods?

2021-01-22 02:06 UTC, sharvaniharan commented
I have removed all unnecessary comments, since our code is self-commenting. Please lmk if we can follow it going forward, or save any comments as is. @dbrant @cooltey

2021-01-22 15:17 UTC, merged