Kotlin conversion: DateUtil
wikimedia/apps-android-wikipedia pull request #1967
Opened 2021-01-23 03:13 UTC by sharvaniharan

2021-01-27 14:05 UTC, dbrant requested changes

2021-01-27 14:05 UTC, dbrant commented on app/src/main/java/org/wikipedia/util/DateUtil.kt
> +    @Throws(ParseException::class)
I don't think we need to explicitly specify `@Throws` annotations anymore.

2021-01-27 14:05 UTC, dbrant commented on app/src/main/java/org/wikipedia/util/DateUtil.kt
> +    private val DATE_FORMATS: MutableMap<String, SimpleDateFormat> = HashMap()
Can be simplified to:
`private val DATE_FORMATS = HashMap<String, SimpleDateFormat>()`

2021-01-29 19:12 UTC, cooltey reviewed
One minor comment

2021-01-29 19:12 UTC, cooltey commented on app/src/main/java/org/wikipedia/util/DateUtil.kt
> +        return getCachedDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'", Locale.ROOT, true)!!.parse(date!!)!!
Please remove `!!` on `date`.

2021-01-29 21:41 UTC, merged