Kotlin conversion: L10nUtil
wikimedia/apps-android-wikipedia pull request #2028
Opened 2021-02-02 20:14 UTC by sharvaniharan

2021-02-02 22:30 UTC, cooltey requested changes

2021-02-02 22:30 UTC, cooltey commented on app/src/main/java/org/wikipedia/util/L10nUtil.kt
> +        return Arrays.binarySearch(RTL_LANGS, lang, null) >= 0
This can be replaced by `RTL_LANGS.binarySearch(lang) >= 0`.

2021-02-02 22:30 UTC, cooltey commented on app/src/main/java/org/wikipedia/util/L10nUtil.kt
> +            AppLanguageLookUpTable.TRADITIONAL_CHINESE_LANGUAGE_CODE, AppLanguageLookUpTable.CHINESE_TW_LANGUAGE_CODE, AppLanguageLookUpTable.CHINESE_HK_LANGUAGE_CODE, AppLanguageLookUpTable.CHINESE_
Would it be possible to import `AppLanguageLookUpTable` to reduce the length of this line?

2021-02-02 22:30 UTC, cooltey commented on app/src/main/java/org/wikipedia/util/L10nUtil.kt
> +    private val currentConfiguration: Configuration
Would it be possible to move this variable method to the top of other methods?

2021-02-02 22:30 UTC, cooltey commented on app/src/main/java/org/wikipedia/util/L10nUtil.kt
> +    val isDeviceRTL: Boolean
Would it be possible to move this variable method to the top of other methods?

2021-02-03 14:31 UTC, dbrant commented
Doesn't seem to build anymore (probably just needs to be updated because of more recent conversions).

2021-02-04 23:50 UTC, merged