Kotlin Conversion: SearchResults
wikimedia/apps-android-wikipedia pull request #2135
Opened 2021-02-24 22:02 UTC by sharvaniharan

2021-02-26 14:46 UTC, dbrant requested changes

2021-02-26 14:46 UTC, dbrant commented on app/src/main/java/org/wikipedia/search/SearchResults.kt
> +    var suggestion: String? = null
This can become a `data class` with these fields in the primary constructor.

2021-03-01 19:00 UTC, dbrant requested changes

2021-03-01 21:41 UTC, sharvaniharan commented on app/src/main/java/org/wikipedia/search/SearchResults.kt
> +        (pages as ArrayList).sortWith { o2, o1 -> (o1?.index()!!.compareTo(o2?.index()!!)) }
Thank you Dmitry!! 🤦‍♀️

2021-03-02 21:56 UTC, cooltey requested changes

2021-03-02 21:56 UTC, cooltey commented on app/src/main/java/org/wikipedia/search/SearchResults.kt
> +        var continuation: Map<String, String>?,
Would it be possible to change `List` to `MutableList`?

2021-03-02 21:56 UTC, cooltey commented on app/src/main/java/org/wikipedia/search/SearchResults.kt
> +    constructor(results: List<SearchResult>) : this(results, null)
Same

2021-03-02 21:56 UTC, cooltey commented on app/src/main/java/org/wikipedia/search/SearchResults.kt
> +    constructor(pages: List<MwQueryPage>, wiki: WikiSite,
Same.

2021-03-02 21:56 UTC, cooltey commented on app/src/main/java/org/wikipedia/search/SearchResults.kt
> +        val searchResults: MutableList<SearchResult> = ArrayList()
If the list is `Mutable`, then we don't need to create this.

2021-03-02 21:56 UTC, cooltey commented on app/src/main/java/org/wikipedia/search/SearchResults.kt
> +        (pages as ArrayList).sortWith { o1, o2 -> (o1?.index()!!.compareTo(o2?.index()!!)) }
The `as ArrayList` can be removed.

2021-03-02 21:56 UTC, cooltey commented on app/src/main/java/org/wikipedia/search/SearchResults.kt
> +        results = searchResults
If the list is `Mutable`, then we don't need to create this.

2021-03-03 18:19 UTC, cooltey commented on app/src/main/java/org/wikipedia/search/SearchResults.kt
> +        (pages).sortWith { o1, o2 -> (o1?.index()!!.compareTo(o2?.index()!!)) }
Parentheses can be removed

2021-03-03 19:11 UTC, merged