DescriptionEditFragment converted to Kotlin
wikimedia/apps-android-wikipedia pull request #2214
Opened 2021-03-16 20:31 UTC by sharvaniharan

2021-03-18 22:50 UTC, cooltey requested changes

2021-03-18 22:50 UTC, cooltey commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +     val binding get() = _binding!!
Please remove unnecessary space.

2021-03-18 22:50 UTC, cooltey commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +    private lateinit var invokeSource: InvokeSource
Please make sure to put `lateinit var` to the top of these values for the reading experience.

2021-03-18 22:50 UTC, cooltey commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +import org.wikipedia.auth.AccountUtil.isLoggedIn
Please import only `org.wikipedia.auth.AccountUtil`.

2021-03-18 22:50 UTC, cooltey commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +            GsonUnmarshaller.unmarshal(PageSummaryForEdit::class.java,
Should it be `targeSummary = ...`?

2021-03-18 22:50 UTC, cooltey commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +        if (invokeSource == InvokeSource.PAGE_ACTIVITY && TextUtils.isEmpty(sourceSummary!!.extractHtml)) {
Please replace `TextUtils.isEmpty`.

2021-03-18 22:50 UTC, cooltey commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +                    .subscribe({ summary: PageSummary -> sourceSummary!!.extractHtml = summary.extractHtml },
Please remove explicit type specification.

2021-03-18 22:50 UTC, cooltey commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +                    .flatMap { mwQueryResponse: MwQueryResponse ->
Please remove explicit type specification.

2021-03-18 22:50 UTC, cooltey commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +                    .subscribe({ result: Edit ->
Please remove explicit type specification.

2021-03-18 22:50 UTC, cooltey commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +                    }) { caught: Throwable -> editFailed(caught, true) })
Please remove explicit type specification.

2021-03-18 22:50 UTC, cooltey commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +                    .flatMap { response: MwQueryResponse ->
Please remove explicit type specification.

2021-03-18 22:50 UTC, cooltey commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +                    .subscribe({ response: EntityPostResponse ->
Please remove explicit type specification.

2021-03-18 22:50 UTC, cooltey commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +                    }) { caught: Throwable ->
Please remove explicit type specification.

2021-03-18 22:50 UTC, cooltey commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +                requireActivity().onBackPressed()
Please remove unnecessary space.

2021-03-18 22:50 UTC, cooltey commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +            callback()!!.onBottomBarContainerClicked(action)
Please use null-safe on `callback()`.

2021-03-18 22:50 UTC, cooltey commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +    }
This is not a readable format, please reformat it.

2021-03-18 22:50 UTC, cooltey commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +        @JvmStatic
Please add an empty line here.

2021-03-18 22:50 UTC, cooltey commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +        const val TEMPLATE_PARSE_REGEX = "(\\{\\{[Ss]hort description\\|(?:1=)?)([^}|]+)([^}]*\\}\\})"
Please remove redundant symbols.

2021-03-18 22:50 UTC, cooltey commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +            instance.arguments = args
We can use `DescriptionEditFragment().apply {}` here.

2021-03-23 20:14 UTC, sharvaniharan commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +        if (activity == null) {
Moved it to the top of the runnable.. lmk if thats ok

2021-03-24 00:31 UTC, sharvaniharan commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +    private var highlightText: String? = null
I am wondering if the source and target summaries should really be null in the beginning?i will change the highlightText..

2021-03-26 16:12 UTC, dbrant requested changes
This crashes upon use. Did you try running and/or using it?

2021-03-26 16:12 UTC, dbrant commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +                                    Handler().postDelayed(successRunnable, TimeUnit.SECONDS.toMillis(4))
since `Handler()` is deprecated, let's switch to using `requireView.postDelayed()`.

2021-03-26 16:12 UTC, dbrant commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +                            Handler().postDelayed(successRunnable, TimeUnit.SECONDS.toMillis(4))
since `Handler()` is deprecated, let's switch to using `requireView.postDelayed()`.

2021-03-26 16:12 UTC, dbrant commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditActivity.kt
> +                intent.getStringExtra(EXTRA_HIGHLIGHT_TEXT)!!,
Hint: it was important for the highlight text to be nullable.

2021-03-26 16:12 UTC, dbrant commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +        csrfClient!!.cancel()
Asking for a crash. Should use `?` instead of `!!`.

2021-04-01 22:13 UTC, cooltey requested changes

2021-04-01 22:13 UTC, cooltey commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +        if (invokeSource == InvokeSource.PAGE_ACTIVITY && sourceSummary!!.extractHtml!!.isEmpty()) {
`sourceSummary!!.extractHtml!!.isEmpty()` can be `sourceSummary?.extractHtml.isNullOrEmpty()`

2021-04-01 22:13 UTC, cooltey commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +                    .subscribe({ summary -> sourceSummary!!.extractHtml = summary.extractHtml },
`sourceSummary!!` can be null safe -> `sourceSummary?.extractHtml`.

2021-04-01 22:13 UTC, cooltey commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +        binding.fragmentDescriptionEditView.setSummaries(requireActivity(), sourceSummary!!, targetSummary)
Should we have a null check on `sourceSummary` like:
```
sourceSummary?.let { }
```

2021-04-01 22:13 UTC, cooltey commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +            }
This is redundant since you have the null safe process below.

2021-04-01 22:13 UTC, cooltey commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +                            }
Would it be better if do something like the below?
```
                          result.edit()?.run {
                              when {
                                  editSucceeded() -> {
                                      requireView().postDelayed(successRunnable, TimeUnit.SECONDS.toMillis(4))
                                      funnel.logSaved(newRevId())
                                  }
                                  hasEditErrorCode() -> {

                                      // TODO: handle AbuseFilter messages
                                      // new EditAbuseFilterResult(result.edit().code(), result.edit().info(), result.edit().warning());
                                      editFailed(IOException(StringUtils.defaultString(warning())), false)
                                  }
                                  hasCaptchaResponse() -> {

                                      // TODO: handle captcha.
                                      // new CaptchaResult(result.edit().captchaId());
                                      funnel.logCaptchaShown()
                                  }
                                  hasSpamBlacklistResponse() -> {
                                      editFailed(IOException(getString(R.string.editing_error_spamblacklist)), false)
                                  }
                                  else -> {
                                      editFailed(IOException("Received unrecognized edit response"), true)
                                  }
                              }   
                          }
```

2021-04-01 22:13 UTC, cooltey commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +            FeedbackUtil.showError(activity!!, caught)
Please use `requireActivity()`.

2021-04-01 22:13 UTC, cooltey commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +        const val TEMPLATE_PARSE_REGEX = "(\\{\\{[Ss]hort description\\|(?:1=)?)([^}|]+)([^}]*\\}\\})"
Is this resolved?

2021-04-01 22:13 UTC, cooltey commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +        const val TEMPLATE_PARSE_REGEX = "(\\{\\{[Ss]hort description\\|(?:1=)?)([^}|]+)([^}]*\\}\\})"
Also, please move to the bottom of these variables for proper order.

2021-04-01 22:13 UTC, cooltey commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +        @JvmStatic
`@JvmStatic` can be removed now.

2021-04-02 21:29 UTC, cooltey requested changes

2021-04-02 21:29 UTC, cooltey commented on app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
> +        const val TEMPLATE_PARSE_REGEX = "(\\{\\{[Ss]hort description\\|(?:1=)?)([^}|]+)([^}]*}})"
Oops, looks like this change causes the crash when opening the `DescriptionEditFragment`, maybe we should add the slashes back and maybe add `Suppress()` for that.

2021-04-05 15:53 UTC, merged