ImgRecs: make bottomsheet draggable
wikimedia/apps-android-wikipedia pull request #2320
Opened 2021-04-16 23:15 UTC by cooltey

2021-04-17 05:39 UTC, sharvaniharan commented
It works really well! at first glance! We only need to adjust the peek height as some fraction of the screen height and we are all set! Great work @cooltey  !! 👏🏼 👏🏼 Will review code in a bit!

2021-04-20 17:54 UTC, sharvaniharan commented
Checking this..

2021-04-20 18:01 UTC, sharvaniharan commented
@cooltey Looks like the peek height is not optimized for small screen?
![peek](https://user-images.githubusercontent.com/9540770/115443103-b1e3eb00-a1c7-11eb-9dd8-e9e1c38dcfbe.png)

We should be able to see the article, no?

2021-04-20 18:02 UTC, sharvaniharan requested changes
Needs to be optimized for small screen.

2021-04-20 21:24 UTC, cooltey commented
> 
> 
> Needs to be optimized for small screen.

Hi @sharvaniharan 
I changed the default visibility of bottom sheet to collapsed with the new peek height, and I'll leave comment to Robin about this change.

2021-04-20 21:40 UTC, sharvaniharan commented
ok @cooltey Will merge it then..

2021-04-20 22:11 UTC, cooltey commented
Thanks @sharvaniharan, please see the comment here https://phabricator.wikimedia.org/T280151#7022461 and merge it if it looks good to you 🙏

2021-04-20 22:54 UTC, sharvaniharan commented on app/src/main/java/org/wikipedia/suggestededits/ImageRecsFragment.kt
> +                            binding.suggestedEditsItemRootView.doViewsOverlap(binding.articleTitle, binding.bottomSheetCoordinatorLayout).run {
👍

2021-04-20 22:55 UTC, merged