Kotlin conversion: Rest of the Funnel classes
wikimedia/apps-android-wikipedia pull request #2379
Opened 2021-04-29 21:33 UTC by sharvaniharan

Wrapped up the Funnel package before starting Butterknife usage.

2021-05-03 20:47 UTC, sharvaniharan commented
Ready for review @cooltey @dbrant

2021-05-03 23:13 UTC, cooltey requested changes

2021-05-03 23:13 UTC, cooltey commented on app/src/main/java/org/wikipedia/analytics/ShareAFactFunnel.kt
> +    private fun logAction(action: String, text: String, shareMode: ShareMode? = null) {
Should we make the `text: String` nullable?

2021-05-03 23:13 UTC, cooltey commented on app/src/main/java/org/wikipedia/analytics/ShareAFactFunnel.kt
> +        }
If the `text` is nullable, would this be better?
```
        val textStr = text.orEmpty().substring(0, MAX_LENGTH.coerceAtMost(text.orEmpty().length))

```

2021-05-03 23:13 UTC, cooltey commented on app/src/main/java/org/wikipedia/analytics/SuggestedEditsFunnel.kt
> +    private val uniqueTitles: MutableList<String> = ArrayList()
Could be `uniqueTitles = mutableListOf<String>()`

2021-05-03 23:13 UTC, cooltey commented on app/src/main/java/org/wikipedia/analytics/SuggestedEditsFunnel.kt
> +            }
Can be `else -> return`

2021-05-03 23:13 UTC, cooltey commented on app/src/main/java/org/wikipedia/analytics/SuggestedEditsFunnel.kt
> +            get() = impressions == 0 && clicks == 0 && suggestionsClicked == 0 && cancels == 0 && successes == 0 && failures == 0
Can be `val isEmpty = impressions ...`

2021-05-03 23:13 UTC, cooltey commented on app/src/main/java/org/wikipedia/analytics/SuggestedEditsFunnel.kt
> +        private const val SUGGESTED_EDITS_API_VERSION = "1.0"
Please have a proper order.

2021-05-03 23:13 UTC, cooltey commented on app/src/main/java/org/wikipedia/analytics/TabFunnel.kt
> +        val params: MutableList<Any> = ArrayList()
Can be `val params = mutableListOf<Any>()`

2021-05-03 23:13 UTC, cooltey commented on app/src/main/java/org/wikipedia/analytics/TimedFunnel.kt
> +        startTime = System.currentTimeMillis()
Can this be initialized at line `11`?

2021-05-03 23:13 UTC, cooltey commented on app/src/main/java/org/wikipedia/analytics/TimedFunnel.kt
> +        get() = TimeUnit.MILLISECONDS.toSeconds(duration)
These can be simplified without having a `get()`.

2021-05-03 23:13 UTC, cooltey commented on app/src/main/java/org/wikipedia/analytics/UserContributionFunnel.kt
> +        private const val REV_ID = 20217330
Please have a proper order.

2021-05-03 23:13 UTC, cooltey commented on app/src/main/java/org/wikipedia/analytics/SuggestedEditsFunnel.kt
> +        }
Looks like these static functions should return non-null variable.

These can be done by adding `!!` or `as SuggestedEditsFunnel`

2021-05-03 23:13 UTC, cooltey commented on app/src/main/java/org/wikipedia/analytics/UserContributionFunnel.kt
> +        }
Looks like this static function should return non-null variable and can be done by adding `!!` or `as UserContributionFunnel`.

2021-05-04 19:21 UTC, sharvaniharan commented on app/src/main/java/org/wikipedia/analytics/AppearanceChangeFunnel.kt
> +        return super.preprocessData(eventData)!!
When we get a non-null eventdata we will definitely send back a non-null JSONObject @cooltey So will change the parent.

2021-05-05 21:15 UTC, merged