Convert PageActivity to Kotlin
wikimedia/apps-android-wikipedia pull request #2413
Opened 2021-05-07 19:49 UTC by cooltey

2021-05-07 22:47 UTC, cooltey commented on app/src/main/java/org/wikipedia/page/PageActivity.java
> -            }
This will be removed since there's no other place sending "isSearching" to the bundle.

2021-05-14 23:55 UTC, sharvaniharan commented
Lgtm... @dbrant please take a look once and merge.

2021-05-27 14:05 UTC, dbrant requested changes

2021-05-27 16:19 UTC, cooltey commented on app/src/main/AndroidManifest.xml
> -        <activity
Not sure why it was deleted. Recovered.

2021-05-28 14:04 UTC, merged