Kotlin Conversion: MwQueryResult, MwQueryPage
wikimedia/apps-android-wikipedia pull request #2737
Opened 2021-08-14 01:11 UTC by sharvaniharan

2021-09-02 15:54 UTC, sharvaniharan commented
resolved @cooltey

2021-09-03 23:10 UTC, cooltey requested changes

2021-09-03 23:10 UTC, cooltey commented on app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryResult.kt
> +        return captchaId
Can it be simplified to `amInfo?.requests?.find { "CaptchaAuthenticationRequest" == it.id }?.fields?.get("captchaId")?.value`?

2021-09-03 23:10 UTC, cooltey commented on app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryResult.kt
> +        val result: MutableList<PageTitle> = ArrayList()
Please remove explicit type specficiation.

2021-09-08 19:34 UTC, merged