Kotlinx Serialization: with a vengeance.
wikimedia/apps-android-wikipedia pull request #2828
Opened 2021-09-21 23:59 UTC by dbrant

This does all of the following:

* Remove the actual dependency on Gson, for real. (except for tests)
* Remove the usage of `@Contextual` annotations, and instead use proper polymorphism specifiers.
* Create serializers for third-party classes (`Date`, `Location`, etc)
* Create a generic facility for serializing/deserializing arbitrary classes, lists, maps, etc. (`JsonUtil`)

2021-09-23 19:47 UTC, cooltey requested changes
Found the following issues:
1. `kotlinx.serialization.SerializationException: Serializer for class 'SessionData' is not found.`
2. `kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 25568: Expected string literal but 'null' literal was found.
    Use 'coerceInputValues = true' in 'Json {}' builder to coerce nulls to default values.` and it causes error when opening the `NotifficationActivity`.
3. `kotlinx.serialization.SerializationException: Serializer for class 'SiteInfo' is not found` in `LangaugesListActivity`.
4. `Class not found when unmarshalling: org.wikipedia.userprofile.Contribution` in `ContributionsDetailsActivity`
5. `Class not found when unmarshalling: org.wikipedia.page.PageTitle` when opening the `EditSectionActivity`.
6. `kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 1282: Unexpected symbol 'n' in numeric literal
    JSON input: .....text": "", "offset": {"from": null,"to": 1965}},{"type": 1, .....` when opening Watchlist `ArticleEditDetailsFragment`

2021-09-23 20:22 UTC, dbrant commented
@cooltey  Great catches:

> 1. `kotlinx.serialization.SerializationException: Serializer for class 'SessionData' is not found.`

Done.

> 2. `kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 25568: Expected string literal but 'null' literal was found. Use 'coerceInputValues = true' in 'Json {}' builder to coerce nulls to default values.` and it causes error when opening the `NotifficationActivity`.

Can't reproduce -- it must be dependent on the exact notifications that you have for you account. Can you paste more info from the exception that you get?

> 3. `kotlinx.serialization.SerializationException: Serializer for class 'SiteInfo' is not found` in `LangaugesListActivity`.

Done.

> 4. `Class not found when unmarshalling: org.wikipedia.userprofile.Contribution` in `ContributionsDetailsActivity`

Can't reproduce. Can you post the full exception you see?

> 5. `Class not found when unmarshalling: org.wikipedia.page.PageTitle` when opening the `EditSectionActivity`.

Can't reproduce. Can you post the full actual exception you see?

> 6. `kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 1282: Unexpected symbol 'n' in numeric literal JSON input: .....text": "", "offset": {"from": null,"to": 1965}},{"type": 1, .....` when opening Watchlist `ArticleEditDetailsFragment`

Done.

2021-09-23 21:51 UTC, cooltey commented
@dbrant 
> > 1. `kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 25568: Expected string literal but 'null' literal was found. Use 'coerceInputValues = true' in 'Json {}' builder to coerce nulls to default values.` and it causes error when opening the `NotifficationActivity`.
> 
> Can't reproduce -- it must be dependent on the exact notifications that you have for your account. Can you paste more info from the exception that you get?

```
2021-09-23 14:48:26.512 7251-7251/org.wikipedia.dev E/org.wikipedia.notifications.NotificationActivity: setErrorState():203: 
    kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 25568: Expected string literal but 'null' literal was found.
    Use 'coerceInputValues = true' in 'Json {}` builder to coerce nulls to default values.
    JSON input: .....在「‪太空部隊‬」的連結通知","description":null,"data":{"tokenType":"csrf.....
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
        at kotlinx.serialization.json.internal.JsonLexer.fail(JsonLexer.kt:479)
        at kotlinx.serialization.json.internal.JsonLexer.unexpectedToken(JsonLexer.kt:196)
        at kotlinx.serialization.json.internal.JsonLexer.consumeNextToken(JsonLexer.kt:188)
        at kotlinx.serialization.json.internal.JsonLexer.consumeKeyString(JsonLexer.kt:298)
        at kotlinx.serialization.json.internal.JsonLexer.consumeString(JsonLexer.kt:318)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeString(StreamingJsonDecoder.kt:245)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeStringElement(AbstractDecoder.kt:58)
        at org.wikipedia.notifications.Notification$Link$$serializer.deserialize(Notification.kt:72)
        at org.wikipedia.notifications.Notification$Link$$serializer.deserialize(Notification.kt:72)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:32)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
        at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:535)
        at kotlinx.serialization.internal.ListLikeSerializer.readElement(CollectionSerializers.kt:80)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:32)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:79)
        at org.wikipedia.notifications.Notification$Links$$serializer.deserialize(Notification.kt:83)
        at org.wikipedia.notifications.Notification$Links$$serializer.deserialize(Notification.kt:83)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:32)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:79)
        at org.wikipedia.notifications.Notification$Contents$$serializer.deserialize(Notification.kt:110)
        at org.wikipedia.notifications.Notification$Contents$$serializer.deserialize(Notification.kt:110)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:32)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:79)
2021-09-23 14:48:26.513 7251-7251/org.wikipedia.dev E/org.wikipedia.notifications.NotificationActivity:     at org.wikipedia.notifications.Notification$$serializer.deserialize(Notification.kt:11)
        at org.wikipedia.notifications.Notification$$serializer.deserialize(Notification.kt:11)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:32)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
        at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:535)
        at kotlinx.serialization.internal.ListLikeSerializer.readElement(CollectionSerializers.kt:80)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:32)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:79)
        at org.wikipedia.dataclient.mwapi.MwQueryResult$NotificationList$$serializer.deserialize(MwQueryResult.kt:144)
        at org.wikipedia.dataclient.mwapi.MwQueryResult$NotificationList$$serializer.deserialize(MwQueryResult.kt:144)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:32)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:79)
        at org.wikipedia.dataclient.mwapi.MwQueryResult$$serializer.deserialize(MwQueryResult.kt:14)
        at org.wikipedia.dataclient.mwapi.MwQueryResult$$serializer.deserialize(MwQueryResult.kt:14)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:32)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:79)
        at org.wikipedia.dataclient.mwapi.MwQueryResponse$$serializer.deserialize(Mw [...]

2021-09-24 14:36 UTC, dbrant commented
@cooltey  Thanks! All of these issues should now be fixed, except the errors that you see about `Class not found when unmarshalling`.  Can you try doing a `Clean Project` and rebuilding, and see if you still have problems?

2021-09-24 20:05 UTC, cooltey commented
> 
> 
> @cooltey Thanks! All of these issues should now be fixed, except the errors that you see about `Class not found when unmarshalling`. Can you try doing a `Clean Project` and rebuilding, and see if you still have problems?

It works for me. I ran `Clean Project` twice and not seeing the error messages anymore.

2021-09-25 00:09 UTC, cooltey requested changes

2021-09-25 00:09 UTC, cooltey commented on app/src/main/java/org/wikipedia/json/DateSerializer.kt
> +    override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("Date", PrimitiveKind.LONG)
Explicit type specification can be removed.

2021-09-25 00:09 UTC, cooltey commented on app/src/main/java/org/wikipedia/json/LocationSerializer.kt
> +    override val descriptor: SerialDescriptor = buildClassSerialDescriptor("Location") {
Explicit type specification can be removed.

2021-09-25 00:09 UTC, cooltey commented on app/src/main/java/org/wikipedia/json/UriSerializer.kt
> +    override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("Uri", PrimitiveKind.STRING)
Explicit type specification can be removed.

2021-09-27 01:07 UTC, sharvaniharan commented
Jsondecoding exceptioin while fetching stream configs
![Screen Shot 2021-09-26 at 6 03 14 PM](https://user-images.githubusercontent.com/9540770/134831340-41716130-040b-4fc6-a72b-a8bc02a06a91.png)

2021-09-27 01:08 UTC, sharvaniharan commented
I am also seeing that when we click on the lead image in an article, the license info doesnt load and progressbar is active infinitely...

2021-09-27 12:27 UTC, dbrant commented on app/src/main/java/org/wikipedia/edit/preview/EditPreviewFragment.kt
> +            (JsonUtil.decodeFromString(messagePayload.toString()) as PageReferences?)?.let {
yes!

2021-09-27 12:38 UTC, dbrant commented on app/src/main/java/org/wikipedia/feed/announcement/AnnouncementClient.kt
> +            return if (announcement.startTime() != null && announcement.startTime()!!.after(date)) {
yes, in fact I made it even more readable than that.

2021-09-27 14:37 UTC, dbrant commented
@sharvaniharan  More good catches!
Should be all fixed now.

2021-09-27 22:25 UTC, cooltey approved these changes

2021-09-28 17:54 UTC, sharvaniharan commented
@dbrant there is an error while loading Notifications.. I think you will get a logcat stack trace for it, please let me know if you dont and I will upload a screenshot.

2021-09-28 18:04 UTC, dbrant commented
@sharvaniharan  I'm not seeing it; please post the stack trace you see. (it probably has to do with the specific notifications you have for your account)

2021-09-28 18:04 UTC, sharvaniharan commented
![Screen Shot 2021-09-28 at 10 52 56 AM](https://user-images.githubusercontent.com/9540770/135141342-c80c1197-724b-4257-9501-70b005c455e7.png)

2021-09-28 18:41 UTC, dbrant commented
@sharvaniharan  ...Fixed!

2021-09-28 21:59 UTC, merged