Update the logic to include all wikis
wikimedia/apps-android-wikipedia pull request #2947
Opened 2021-10-29 01:16 UTC by sharvaniharan

When "All Wikis" option is selected, we need to fetch notifications from all wikis including metawiki, commonswiki etc
When there is at least one filter then we fetch only wikis that are selected and within `appLanguagecodes`.
`val langCode = (if (it.endsWith("wiki")) it.substring(0, it.length - "wiki".length) else it)`
The above manipulation is to accommodate wikis like `wikidata` whicch, with a simple replace would have resulted in `datawiki` instead of `wikidatawiki`

2021-10-29 18:24 UTC, sharvaniharan commented on app/src/main/java/org/wikipedia/notifications/NotificationActivity.kt
> +            (if (allWikisSelected()) dbNameMap.keys else NotificationsFilterActivity.allWikisList()).filterNot { excludedWikiCodes.contains(it) }.map {
@dbrant @cooltey I removed the check for `allWikisSelected()`, just felt that this way they will still see the notifications from other wikis like meta, mediawiki, etc, no matter what their filter... what do you feel about it?

2021-10-29 19:48 UTC, cooltey requested changes

2021-10-29 19:48 UTC, cooltey commented on app/src/main/java/org/wikipedia/notifications/NotificationActivity.kt
> +            (dbNameMap.keys.plus(NotificationsFilterActivity.allWikisList())).filterNot { excludedWikiCodes.contains(it) }.map {
It feels not quite right here.

The `dbNameMap.keys` contains something like `commonswiki`, but the `NotificationsFilterActivity.allWikisList()` contains language codes without `wiki`. Looks like the `filterNot` will not filter correctly at this point.

Can we do something like: `(dbNameMap.keys.plus(NotificationsFilterActivity.allWikisList().map { (WikipediaApp.getInstance().language().getDefaultLanguageCode(it) ?: it) + "wiki" }`?

Please note that I didn't check the `zh-yue` if that also works for it.

2021-11-02 19:18 UTC, dbrant commented
fixed via #2950

2021-11-02 19:18 UTC, closed without merging