Poll notifications in a JobService
wikimedia/apps-android-wikipedia pull request #3032
Opened 2021-12-08 23:24 UTC by sharvaniharan

2021-12-09 14:47 UTC, dbrant requested changes
Great; This is basically what it needs to be, but there's one little bit that's missing:
As I understand it, if we're going to use `JobService`, we need to take care to call the `jobFinished()` function at the end of our job, to signal to the system that the job is complete. Otherwise the system will hold on to the wakelock longer than necessary.

(let's call `jobFinished()` at the end of the success case and the error case in the `pollNotifications` coroutine.)

Additional stuff inline.

2021-12-09 14:47 UTC, dbrant commented on app/src/main/java/org/wikipedia/util/JobsUtil.kt
> +    fun schedulePollNotificationJob(context: Context) {
Can this be placed in a companion object of `PollNotificationService` itself, instead of a separate file?

2021-12-09 14:47 UTC, dbrant commented on app/src/main/java/org/wikipedia/notifications/PollNotificationService.kt
> +                NotificationPollBroadcastReceiver.assertLoggedIn()
The `assertLoggedIn()` function can be moved into this class, and made private.

2021-12-09 14:47 UTC, dbrant commented on app/src/main/java/org/wikipedia/notifications/PollNotificationService.kt
> +    suspend fun retrieveNotifications(context: Context) {
Can be private.

2021-12-10 18:57 UTC, dbrant requested changes

2021-12-10 18:57 UTC, dbrant commented on app/src/main/java/org/wikipedia/notifications/PollNotificationService.kt
> +        jobParameters = p0
Shouldn't we assign `jobParameters` when the job is started, instead of stopped?

2021-12-10 18:57 UTC, dbrant commented on app/src/main/java/org/wikipedia/notifications/PollNotificationService.kt
> +        var pollNotificationService = PollNotificationService()
Instances of `Service` classes are created by the system. Keeping our own instance of a Service class is not correct.

2021-12-10 18:57 UTC, dbrant commented on app/src/main/java/org/wikipedia/notifications/PollNotificationService.kt
> +            pollNotificationService.jobFinished(pollNotificationService.jobParameters, false)
You're finishing the job of a Service class that was never created by the OS, so this will not do anything.

2021-12-10 18:57 UTC, dbrant commented on app/src/main/java/org/wikipedia/notifications/PollNotificationService.kt
> +        pollNotifications(this)
You can pass `jobParameters` on to the `pollNotifications()` function, and finish the job at the end of the coroutine (success case and error case) in that function.  (And not need to keep `jobParameters` as a class property.)

2021-12-11 00:32 UTC, Isira-Seneviratne commented
Couldn't [AndroidX Work](https://developer.android.com/reference/androidx/work/package-summary) be used for this?

2021-12-13 14:37 UTC, merged