Multi-selection of Edit History items for comparison.
wikimedia/apps-android-wikipedia pull request #3152
Opened 2022-02-25 20:36 UTC by dbrant

https://phabricator.wikimedia.org/T299180

2022-03-02 19:49 UTC, cooltey requested changes
The code looks good to me, but some places may be optimized:
1. When in "compare" mode, the back button should be able to cancel the "compare" mode.
2. Should we make the whole item togglable when in "compare" mode instead of leading the user to the detail view when clicking on the item? Feel like only making the radio button togglable is not enough.
3. According to the design, the first item should be yellow, and the second one should be blue.

2022-03-02 19:49 UTC, cooltey commented on app/src/main/java/org/wikipedia/page/edithistory/EditHistoryItemView.kt
> +            // TODO
Should we show a menu here?

2022-03-04 14:56 UTC, dbrant commented on app/src/main/java/org/wikipedia/page/edithistory/EditHistoryItemView.kt
> +            // TODO
This will be handled in #3113

2022-03-04 14:57 UTC, dbrant commented
> 1. When in "compare" mode, the back button should be able to cancel the "compare" mode.

Done!

> 2. Should we make the whole item togglable when in "compare" mode instead of leading the user to the detail view when clicking on the item? Feel like only making the radio button togglable is not enough.
> 3. According to the design, the first item should be yellow, and the second one should be blue.

These two items will be discussed in Design review, since there are some inconsistencies in the designs.

2022-03-04 18:27 UTC, merged