Add Rollback button and Undo to Diff View
wikimedia/apps-android-wikipedia pull request #3374
Opened 2022-06-01 19:46 UTC by cooltey

https://phabricator.wikimedia.org/T303547

2022-06-09 15:23 UTC, cooltey commented
@dbrant It is ready for review.

2022-06-10 19:33 UTC, dbrant requested changes

2022-06-10 19:33 UTC, dbrant commented on app/src/main/res/values/strings.xml
> +    <string name="edit_diff_bytes">%s bytes</string>
Should this be `plurals`?

2022-06-10 23:59 UTC, cooltey commented on app/src/main/res/values/strings.xml
> +    <string name="edit_diff_bytes">%s bytes</string>
Yes! Done.

2022-06-13 19:23 UTC, merged