Design updates in Editing activity.
wikimedia/apps-android-wikipedia pull request #3511
Opened 2022-08-01 20:45 UTC by dbrant

https://phabricator.wikimedia.org/T313223

2022-09-19 17:26 UTC, dbrant commented
@cooltey @sharvaniharan  This is now ready. Mea culpa for the size.

2022-09-19 22:00 UTC, cooltey requested changes
Excellent upgrade! 💯

2022-09-20 14:05 UTC, dbrant commented on app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
> +            val searchIntent = SearchActivity.newIntent(this@EditSectionActivity, Constants.InvokeSource.EDIT_ACTIVITY, null, true)
yep

2022-09-20 14:05 UTC, dbrant commented on app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
> +        supportActionBar?.elevation = DimenUtil.dpToPx(4f)
yes!

2022-09-20 14:05 UTC, dbrant commented on app/src/main/java/org/wikipedia/theme/ThemeChooserDialog.kt
> +                })
yes

2022-09-22 20:35 UTC, merged