T271944: Refactor LinkPreviewDialog to use ViewModel
wikimedia/apps-android-wikipedia pull request #3596
Opened 2022-09-25 14:23 UTC by fahime-ghasemi

2022-09-26 19:57 UTC, dbrant requested changes
Thanks, a few comments so far:

One of the purposes of switching to a ViewModel structure is to move away from using RxJava. We can simply switch to making network calls directly (updating the network calls to be `suspend` functions, and calling them inside a coroutine with `IO` context). That way, we don't have to manually manage any `disposable` objects, and get rid of the Rx dependency.  For examples, see some of the other `*ViewModel.kt` classes throughout the project.

Otherwise this is just moving code from one place to another, without much meaningful enhancement.

2022-09-27 07:34 UTC, fahime-ghasemi commented
@dbrant Thanks for your comment. I'm happy to hear that I can use suspend functions. I'll change the PR and use suspend functions to get rid of RX dependencies.

2022-09-29 03:56 UTC, mrsangjunboon2018 commented
...

2022-10-07 14:37 UTC, dbrant requested changes
_Much_ better! Just a few minor remaining comments.

2022-10-07 14:37 UTC, dbrant commented on app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt
> +//        viewModel.loadContent()
Remove the comment, please

2022-10-07 14:37 UTC, dbrant commented on app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt
> +        funnel = LinkPreviewFunnel(WikipediaApp.instance, viewModel.historyEntry.source)
Let's move this creation of the `funnel` object up _before_ the call to `renderViewStates()` function. Currently there can be a state where a uiState is reached before `funnel` is initialized.

2022-10-07 14:37 UTC, dbrant commented on app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt
> +        }
This can all be done in the ViewModel, and then pass back the `PageSummary` instead of `Response<PageSummary>`.

2022-10-07 14:37 UTC, dbrant commented on app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewViewModel.kt
> +
kotlin lint: needless blank line.

2022-10-07 14:37 UTC, dbrant commented on app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewViewModel.kt
> +}
kotlin lint: newline required at end of file.

2022-10-07 14:37 UTC, dbrant commented on app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewViewState.kt
> +}
kotlin lint: newline required at end of file.

2022-10-07 14:37 UTC, dbrant commented on app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewViewState.kt
> +
kotlin lint: needless blank line.

2022-10-07 14:37 UTC, dbrant commented on app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewViewState.kt
> +import retrofit2.Response
unused import.

2022-10-07 14:37 UTC, dbrant commented on app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewViewModel.kt
> +
kotlin lint: needless blank line.

2022-10-07 14:37 UTC, dbrant commented on app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewViewModel.kt
> +            {
kotlin lint: curly brace should be on previous line.

2022-10-07 14:37 UTC, dbrant commented on app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewViewModel.kt
> +                {
kotlin lint: curly brace should be on previous line.

2022-10-09 19:58 UTC, fahime-ghasemi commented
@dbrant Thanks for your comments. I applied them.

2022-10-11 14:26 UTC, merged