Exit dialog when users accidentally quit new topic
wikimedia/apps-android-wikipedia pull request #3674
Opened 2022-11-03 16:48 UTC by sharvaniharan

**Phab**: https://phabricator.wikimedia.org/T321269

2022-11-03 20:57 UTC, cooltey requested changes

2022-11-03 20:57 UTC, cooltey commented on app/src/main/res/values/strings.xml
> +    <string name="talk_new_topic_exit_dialog_message">The subject and content text will not be saved </string>
Should we add an ending period to this sentence?

2022-11-03 20:57 UTC, cooltey commented on app/src/main/java/org/wikipedia/talk/TalkReplyActivity.kt
> +            linkHandler = TalkLinkHandler(this)
Please remove empty spaces here.

2022-11-03 20:57 UTC, cooltey commented on app/src/main/java/org/wikipedia/talk/TalkReplyActivity.kt
> +        if (invokeSource == TALK_TOPICS_ACTIVITY &&
Should we use `viewModel.isNewTopic` here instead of the `invokeSource`?

2022-11-03 20:57 UTC, cooltey commented on app/src/main/java/org/wikipedia/talk/TalkReplyActivity.kt
> +        invokeSource = intent.getSerializableExtra(INTENT_EXTRA_INVOKE_SOURCE) as Constants.InvokeSource
Can we use `viewModel.isNewTopic` here instead of having the `invokeSource` here?

2022-11-30 17:50 UTC, sharvaniharan commented
@cooltey @dbrant This is ready for review - passed design review.

2022-11-30 20:08 UTC, merged