Use ViewModel in WatchlistFragment
wikimedia/apps-android-wikipedia pull request #3752
Opened 2023-01-10 22:26 UTC by cooltey

This is a pre-work for this ticket: https://phabricator.wikimedia.org/T326648

2023-01-13 17:57 UTC, cooltey commented on app/src/main/java/org/wikipedia/watchlist/WatchlistViewModel.kt
> +    val uiState = _uiState
I believed I followed the Android Developer example at the time when I started learning how to implement the `Flow`, but looks like they updated it with proper variables which are mutable vs non-mutable.
```
private val _uiState = MutableStateFlow(DiceUiState())
val uiState: StateFlow<DiceUiState> = _uiState.asStateFlow()

```
https://developer.android.com/topic/libraries/architecture/viewmodel

Anyway, I updated the code with a single `uiState` and it should be fine.

2023-01-16 00:30 UTC, jaelsonwagner commented on app/src/main/java/org/wikipedia/watchlist/WatchlistViewModel.kt
> +    val uiState = _uiState
Using a private variable (with underscore) doesn't expose a MutableStateFlow type. So, we use an public variable (without underscore) to just expose a StateFlow type. That way, the consumer can't mutate the state.

2023-01-17 15:29 UTC, dbrant requested changes

2023-01-18 21:33 UTC, cooltey commented on app/src/main/java/org/wikipedia/watchlist/WatchlistFragment.kt
>          fetchWatchlist(false)
Makes sense and done.

2023-01-20 15:42 UTC, merged