Add previews for reading list receive flow
wikimedia/apps-android-wikipedia pull request #3829
Opened 2023-02-14 01:10 UTC by cooltey

https://phabricator.wikimedia.org/T327903

2023-02-15 14:42 UTC, dbrant requested changes

2023-02-15 19:02 UTC, cooltey commented on app/src/main/res/values/strings.xml
> +    <string name="reading_lists_preview_header_title">Shared list</string>
Done.

2023-02-24 20:31 UTC, sharvaniharan requested changes
Just a minor suggestion before merging : 
If the user chooses to `Save` the list, and unSelects all the articles in the list, currently an empty `new` list is created. We can probably disable save if they do not unSelect all?

2023-02-27 21:56 UTC, cooltey commented
> Just a minor suggestion before merging : If the user chooses to `Save` the list, and unSelects all the articles in the list, currently an empty `new` list is created. We can probably disable save if they unSelect all?

Nice catch and it has been fixed!

2023-03-01 20:47 UTC, merged