ABC test logic for machine generated article descriptions
wikimedia/apps-android-wikipedia pull request #3893
Opened 2023-03-18 00:40 UTC by sharvaniharan

**Phab:** https://phabricator.wikimedia.org/T329905

Test name : mBart25
Number of groups: 3
Random but not equal test groups:
Group 1: Of the people who qualify to see [Wikis falling into the available languages], This group will not be shown the suggestions
Group2: They will be shown suggestions only if they are not articles that are biographies of living persons [BLPs]
Group3: They will see both BLP and non-BLP suggestions.

2023-03-18 00:41 UTC, sharvaniharan commented
On hold just to clarify some suggestions from Jaz. Please feel free to do a cursory review.

2023-03-20 20:51 UTC, sharvaniharan commented
Jazmin has confirmed that the group2 users will remain in that group even if they happen to cross the 50 edit mark during the experiment and will not be bumped up

2023-03-22 00:12 UTC, cooltey requested changes

2023-03-22 00:12 UTC, cooltey commented on app/src/main/java/org/wikipedia/analytics/eventplatform/ABTest.kt
> +                    totalContributions += wikidataResponse.await().query?.userInfo!!.editCount
Can we have a `null`-safe condition here? `.query?.userInfo?.editCount ?: 0`

2023-03-22 00:12 UTC, cooltey commented on app/src/main/java/org/wikipedia/analytics/eventplatform/ABTest.kt
> +        const val GROUP_SIZE_2 = 2
Unused value?

2023-03-22 00:12 UTC, cooltey commented on app/src/main/java/org/wikipedia/analytics/eventplatform/ABTest.kt
> +        const val GROUP_2 = 1
Unused value?

2023-03-22 18:25 UTC, cooltey requested changes

2023-03-23 00:41 UTC, sharvaniharan commented on app/src/main/java/org/wikipedia/analytics/eventplatform/ABTest.kt
> +            PrefsIoUtil.setInt(AB_TEST_KEY_PREFIX + abTestName, group)
Good catch .. thanks 😅

2023-03-23 23:06 UTC, merged