Use TypedArray.use() extension
wikimedia/apps-android-wikipedia pull request #4225
Opened 2023-10-08 00:21 UTC by Isira-Seneviratne

2023-10-10 19:14 UTC, cooltey commented
Thanks for the PR. May I know the advantage of using the extension in this case? Otherwise, it would be better if we kept the code as it is.

2023-10-12 01:54 UTC, Isira-Seneviratne commented
> Thanks for the PR. May I know the advantage of using the extension in this case? Otherwise, it would be better if we kept the code as it is.

It works much like the standard Kotlin `use` extension, by recycling the `TypedArray` after returning a value.

2023-11-01 18:24 UTC, cooltey requested changes

2023-11-01 18:24 UTC, cooltey commented on app/src/main/java/org/wikipedia/views/CircularProgressBar.kt
> -                maxProgressValue = getInt(R.styleable.CircularProgressBar_maxProgress, MAX_PROGRESS).toDouble()
Please make sure to apply `maxProgressValue` in the code.

2023-11-03 00:25 UTC, merged