Nearby: Search
wikimedia/apps-android-wikipedia pull request #4319
Opened 2023-12-05 01:34 UTC by sharvaniharan

**Phab:** https://phabricator.wikimedia.org/T351158

2023-12-16 02:09 UTC, sharvaniharan commented on app/src/main/java/org/wikipedia/places/PlacesActivity.kt
> -        fun newIntent(context: Context, wiki: WikiSite, pageTitle: PageTitle? = null, location: Location? = null): Intent {
Persisting the code for places makes this redundant and can always fallback to app language or get it from pageTitle from special cases.

2023-12-16 02:11 UTC, sharvaniharan commented on app/src/main/java/org/wikipedia/places/PlacesFragment.kt
> -                goToLastKnownLocation(1000, viewModel.location, viewModel.pageTitle != null)
@cooltey I removed this change as the zoom was not that much different between 15.99 and 15. Instead it now enlarges the icon. Robin has mentioned 2x in the specs but I have settled for 1.75. will discuss this during design review.

2023-12-16 02:15 UTC, sharvaniharan commented
Open for review :-)

2024-01-05 17:15 UTC, dbrant requested changes
This change seems to cause some weird behavior when panning through the map by small amounts. The markers seem to change from one batch to another completely different batch:

https://github.com/wikimedia/apps-android-wikipedia/assets/1682214/424ef9ed-2b2d-49fb-870d-f6410ff4f852

This does not happen in the base Places branch:

https://github.com/wikimedia/apps-android-wikipedia/assets/1682214/d4bd7e9f-d012-4abf-9f0c-417bca7af139

2024-01-05 20:03 UTC, sharvaniharan commented
@dbrant It is actually happening on both places. In the base branch video, if you see at the :20 second mark, some of the markers disappear. In this branch it is more pronounced because I have removed the "minimum distance to move before updating markers" condition. I believe the root cause is the cache size we have and the logic around it to remove the oldest marker from the AnnotationCache when we max the cache size. I feel removing the minimum distance moved logic made the marker update experience much better, so I am thinking i will keep that and try to increase cache size and check performance.

2024-01-05 20:28 UTC, dbrant commented
> @dbrant It is actually happening on both places. In the base branch video, if you see at the :20 second mark, some of the markers disappear. In this branch it is more pronounced because I have removed the "minimum distance to move before updating markers" condition. I believe the root cause is the cache size we have and the logic around it to remove the oldest marker from the AnnotationCache when we max the cache size. I feel removing the minimum distance moved logic made the marker update experience much better, so I am thinking i will keep that and try to increase cache size and check performance.

I'm not sure I agree.  I think the root cause is that the calculation of the `searchRadius` was moved to an incorrect location.  It looks like it's now calculated when the map is first initialized, which would give it an arbitrarily large radius. The radius should be calculated just before the API call is made (i.e. it should always be the current size of the viewport.)

And because you're making an API call with a huge radius, the returned items could be arbitrarily far, and in an arbitrary order, and will therefore clobber our cache of markers.

2024-01-06 01:27 UTC, sharvaniharan commented
@dbrant That is a very good catch. I have fixed that, but just that doesnt still fix the issue, as at a given zoom level and a heavy article activity area, we can have more than 64 markers. So i had the same issue after the searchRadius fix as well

https://github.com/wikimedia/apps-android-wikipedia/assets/9540770/d4da5c6e-e519-48a9-8be3-a4cacef09ec0

Increasing the cache size along with the searchRadius fix, fixes it, but we can discuss the best cache size in our sync

https://github.com/wikimedia/apps-android-wikipedia/assets/9540770/786f3aa2-bce2-473d-9872-7a23651b6d25

2024-01-12 13:37 UTC, dbrant commented
Merging to keep things moving (and so that Design can have a single APK to test with).
Please look for code review / design feedback on the feature branch.

2024-01-12 13:37 UTC, merged