Places Filter screen: Design tweaks
wikimedia/apps-android-wikipedia pull request #4383
Opened 2024-01-14 01:03 UTC by sharvaniharan

2024-01-17 18:28 UTC, dbrant requested changes

2024-01-17 18:28 UTC, dbrant commented on app/src/main/res/values/styles.xml
> -        <item name="android:background">?attr/paper_color</item>
Removing this attribute introduces significant regressions in the appearance of other Toolbars. e.g. in MainActivity, upon scrolling down. This attribute should be kept, until we refactor all other Toolbars to have the same background color.

2024-01-17 18:28 UTC, dbrant commented on app/src/main/java/org/wikipedia/places/PlacesFilterActivity.kt
> +        supportActionBar?.setBackgroundDrawable(ColorDrawable(ResourceUtil.getThemedColor(this, R.attr.background_color)))
To have full control of the style and color of a Toolbar, an activity should have its own explicit Toolbar in its layout (i.e. not using `style/AppTheme.ActionBar`).

2024-01-17 18:28 UTC, dbrant commented on app/src/main/java/org/wikipedia/places/PlacesFilterActivity.kt
> +            radio.visibility = if (languageCode == Prefs.placesWikiCode) View.VISIBLE else View.INVISIBLE
Was there an issue with using `isVisible`? It seems a bit more clean.

2024-01-17 18:28 UTC, dbrant commented on app/src/main/res/layout/view_places_filter_item.xml
> +            android:background="?attr/selectableItemBackground"
This view doesn't need its own `selectableItemBackground`, since the parent view already has it.

2024-01-18 01:01 UTC, sharvaniharan commented
Done @dbrant. Thank you.

2024-01-18 16:13 UTC, merged