Saved messages flow for edit patrol
wikimedia/apps-android-wikipedia pull request #4483
Opened 2024-02-24 01:51 UTC by sharvaniharan

**Phab:** https://phabricator.wikimedia.org/T356774

2024-03-22 00:14 UTC, cooltey requested changes
- When select an example message and want to go back to the list, it will not stay at the previous "Example message" tab.
- I am still able to swipe-to-delete on the example messages, is that expected?
- After removing the example messages, and tapping on "Undo", the message will be saved as a custom message (My messages).

2024-03-22 00:14 UTC, cooltey commented on app/src/main/java/org/wikipedia/talk/template/TalkTemplatesFragment.kt
> +        menu.findItem(R.id.menu_edit_messages).isVisible = binding.talkTemplatesTabLayout.selectedTabPosition == 0
Can we hide the button when there are no messages in the list as well?

2024-03-22 00:14 UTC, cooltey commented on app/src/main/java/org/wikipedia/talk/template/TalkTemplatesFragment.kt
> +    private var touchCallback: SwipeableItemTouchHelperCallback? = null
Is it possible to change this to `lateinit var` so we do not need to worry about checking the `null`?

2024-03-22 00:14 UTC, cooltey commented on app/src/main/res/values/styles.xml
> +    </style>
We have already used a `MaterialToolbar` in the fragment, would it be possible to add a `TextView` instead of applying a style on a menu item?

2024-03-22 21:04 UTC, sharvaniharan commented
Done @cooltey

2024-03-22 23:00 UTC, cooltey requested changes

2024-03-22 23:00 UTC, cooltey commented on app/src/main/res/values/styles.xml
> +    </style>
Can we remove this style?

2024-03-23 01:59 UTC, sharvaniharan commented on app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsRecentEditsFragment.kt
> +                    val pageTitle = PageTitle(UserAliasData.valueFor(viewModel.wikiSite.languageCode), "", viewModel.wikiSite)
Since this is the list of edits, i have added account's username.

2024-03-23 02:00 UTC, sharvaniharan commented on app/src/main/java/org/wikipedia/talk/TalkReplyActivity.kt
> +                    .putExtra(EXTRA_SAVED_TEMPLATE, isSavedTemplate)
Moved these. I have used them to distinguish between the modes in which we use them.

2024-03-25 19:46 UTC, dbrant requested changes
A few initial major observations, before delving into the code itself:

* It doesn't actually do what it's intended to do; upon publishing a message to a talk page, the triple-brace keywords don't get filled in:
![Screenshot_20240325_152115](https://github.com/wikimedia/apps-android-wikipedia/assets/1682214/20e8dd35-41b5-4616-99ce-bd8854a4f1da)

* There are a number of design mismatches/inconsistencies, particularly in Dark mode:

The "external link" icon has incorrect tint, and appears to be too small (design specifies 24dp):
![image](https://github.com/wikimedia/apps-android-wikipedia/assets/1682214/c4e40613-571f-42e9-9740-61e15a59522b)

The popup dialog for saving the message has incorrect colors in dark mode:
![image](https://github.com/wikimedia/apps-android-wikipedia/assets/1682214/cbc51715-4e8d-4546-97fa-05e385c4e677)

We should ellipsize (...) the message text in the list of messages, instead of cutting it off at the end:
![image](https://github.com/wikimedia/apps-android-wikipedia/assets/1682214/3596d4a0-493d-4dbb-b482-d449e465b550)

The FAB icon looks a bit too large. It looks like the SVG asset itself was imported weirdly, and doesn't have the correct size of 24dp.
![image](https://github.com/wikimedia/apps-android-wikipedia/assets/1682214/a4e1842b-f0ea-4309-9b66-e595e988cf1d)

2024-03-25 23:16 UTC, cooltey commented
Hi @dbrant, the comments you posted have been addressed. Thanks.

2024-03-26 13:37 UTC, merged