Use SavedStateHandle in view models
wikimedia/apps-android-wikipedia pull request #4875
Opened 2024-08-19 09:31 UTC by Isira-Seneviratne

Simplify the view models by using [`SavedStateHandle`](https://developer.android.com/reference/androidx/lifecycle/SavedStateHandle) instead of `Bundle`.

2024-08-19 14:00 UTC, dbrant requested changes
Thanks -- this looks like it will be a worthwhile change. However, a change of this size requires a _much better description_.
The word "simplify" is not meaningful enough. There is a considerable reduction in code, but _why_ is there a reduction in code?

Is it because `SavedStateHandle` automatically provides access to the Activity's intent extras and/or the Fragment's arguments? If so, this should be very clearly specified in your description. I'm not even seeing this described in Google's own documentation of `SavedStateHandle`, which worries me a bit. Can you point to where in the documentation does it endorse using `SavedStateHandle` in this way?

2024-08-19 23:05 UTC, machado001 requested changes
Minor comments =)

2024-08-19 23:20 UTC, Isira-Seneviratne commented on app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListViewModel.kt
> -import kotlinx.coroutines.*
That wasn't intentional, thanks for pointing it out.

2024-08-19 23:57 UTC, machado001 approved these changes

2024-09-29 15:21 UTC, trietbui85 commented
This PR gets bigger and bigger. Should we separate it to multiple smaller PRs?

2024-10-22 15:56 UTC, merged