Refining Espresso test
wikimedia/apps-android-wikipedia pull request #5086
Opened 2024-11-04 19:11 UTC by Williamrai

### What does this do?
This refines the espresso smoke test. Introduces Robot pattern which separates the test into different classes based on specific screen or utility. 

### Why is this needed?
This is needed so that we can 
1. improve code organization 
2. improve test readability
3. developers can update and add test code easily  
4. developers can compose test easily  

**Phabricator:**
https://phabricator.wikimedia.org/T358021

2024-11-13 16:16 UTC, dbrant requested changes

2024-11-13 16:16 UTC, dbrant commented on app/src/main/java/org/wikipedia/test/MainActivity.kt
This seems to have moved MainActivity and MainFragment to the `test` package? I'm not sure that's desired.

2024-11-13 21:10 UTC, Williamrai commented on app/src/main/java/org/wikipedia/test/MainActivity.kt
i updated the name for all directories instead of just the android test directories. Fixed.

2024-11-14 14:06 UTC, dbrant commented
🎉 A solid foundation for the future of our instrumented tests!

2024-11-14 14:06 UTC, merged