Upgrade to SDK 35
wikimedia/apps-android-wikipedia pull request #5169
Opened 2024-12-06 21:06 UTC by cooltey

The #5149 has been merged and it's time to upgrade to SDK 35 officially.

2024-12-06 21:21 UTC, dbrant commented
The activity that will still need some tweaking is PageActivity (and maybe a couple of others):

![image](https://github.com/user-attachments/assets/a6cfaded-a4a0-47d1-803c-60933751eef0)

Notice that the activity bleeds into the status bar at the top, _and_ the navigation bar at the bottom. I believe this is because PageActivity is already "trying" to handle insets correctly, but just needs to be updated to handle top and bottom insets.

2024-12-06 21:26 UTC, cooltey commented
> The activity that will still need some tweaking is PageActivity (and maybe a couple of others):
> 
> ![image](https://private-user-images.githubusercontent.com/1682214/393406522-a6cfaded-a4a0-47d1-803c-60933751eef0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MjA1NDksIm5iZiI6MTczMzUyMDI0OSwicGF0aCI6Ii8xNjgyMjE0LzM5MzQwNjUyMi1hNmNmYWRlZC1hNGEwLTQ3ZDEtODAzYy02MDkzMzc1MWVlZjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDZUMjEyNDA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2VjYTUzNjIzMTYzMzE1ZDUzNzk4MjhlNDE2ZGMzMzljNDAwN2Y4YjYyZGI4ZDhlMTFkYTc1MDQwNGZlOGEyZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.H-VLzsSFJRmLtfprTKVZS_Cnnvmm1iNTxryHRCb-Azk)
> 
> Notice that the activity bleeds into the status bar at the top, _and_ the navigation bar at the bottom. I believe this is because PageActivity is already "trying" to handle insets correctly, but just needs to be updated to handle top and bottom insets.

Thanks for the tips! I'll make updates for those screens that got affected!

2024-12-07 01:07 UTC, cooltey commented
> The activity that will still need some tweaking is PageActivity (and maybe a couple of others):
> Notice that the activity bleeds into the status bar at the top, _and_ the navigation bar at the bottom. I believe this is because PageActivity is already "trying" to handle insets correctly, but just needs to be updated to handle top and bottom insets.

This is fixed. I also fixed the `BottomSheet` presentation, but it is imperfect. The navigation bar color change function does not work properly.
<img src="https://github.com/user-attachments/assets/6efe7f6b-2e5a-4b51-85c3-293d2e7e0545" width="350" />

2024-12-09 20:34 UTC, dbrant requested changes

2024-12-09 21:02 UTC, cooltey commented on app/src/main/java/org/wikipedia/page/ExtendedBottomSheetDialogFragment.kt
> +            DeviceUtil.setNavigationBarColor(it, ResourceUtil.getThemedColor(requireContext(), R.attr.warning_color))
😅  fixed.

2024-12-11 19:39 UTC, dbrant approved these changes

2024-12-11 19:39 UTC, merged