Cleanup Contribution Dashboard
wikimedia/apps-android-wikipedia pull request #5192
Opened 2024-12-23 17:54 UTC by Williamrai

### What does this do?
removes Contribution Dashboard

**Phabricator:**
https://phabricator.wikimedia.org/T382036

2025-01-03 21:11 UTC, cooltey requested changes
Please also remove the following classes:
```
DonorHistoryViewModel
DonorStatus
```

and the preferences:

```
hasDonorHistorySaved
isDonor
isRecurringDonor
```

2025-01-06 15:53 UTC, Williamrai commented
> Please also remove the following classes:
> 
> ```
> DonorHistoryViewModel
> DonorStatus
> ```
> 
> and the preferences:
> 
> ```
> hasDonorHistorySaved
> isDonor
> isRecurringDonor
> ```

The ticket says to keep the logic that persists the user's donation history.

2025-01-06 22:38 UTC, cooltey commented on app/src/main/java/org/wikipedia/settings/Prefs.kt
> -
Please also remove the preference keys from the XML as well.

2025-01-07 14:24 UTC, Williamrai commented on app/src/main/java/org/wikipedia/settings/Prefs.kt
> -
done.

2025-01-07 23:45 UTC, cooltey approved these changes

2025-01-07 23:45 UTC, merged