[WIP] Feat: T380662
wikimedia/apps-android-wikipedia pull request #5196
Opened 2024-12-29 02:49 UTC by cesonha

### Please Read
This is my first open source contribution and this PR is still a work in progress, I hope you can help me understand how can I put the translation and if this class is easily testable, but I will take my time to see how can i write some automated tests for it.

### What does this do?
This will add a new preference in the SettingsFragment that enables the user to delete the local donation history.

### Why is this needed?
Please refer to the Phabricator's link Background section
**Phabricator:**
https://phabricator.wikimedia.org/T380662

2024-12-29 02:52 UTC, cesonha commented
Hi everyone, this is my first contribution and I have some doubts that I would be happy to get some clarification:

- I saw that the iOS and Android Settings screen have a different UI and the preferences are organized in different sections, how can I know that the way I did is approved by the UX/UI team?
- What should I do regarding the translation/localization, do I need to do it by myself?
- What about unit tests, I understand that some classes might be easier to test than others, is there a discussion for that? I want to add tests to my PR but some guidance would be nice!

2025-01-03 20:37 UTC, cooltey commented
Hi @cesonha, thanks for submitting the PR!

> Hi everyone, this is my first contribution and I have some doubts that I would be happy to get some clarification:
> 
>     * I saw that the iOS and Android Settings screen have a different UI and the preferences are organized in different sections, how can I know that the way I did is approved by the UX/UI team?

If you have claimed the ticket, you can tag [HNordeenWMF](https://phabricator.wikimedia.org/p/HNordeenWMF/) or [SChekfa-WMF](https://phabricator.wikimedia.org/p/SChekfa-WMF/) by attaching the screenshot you have in the comment.

>     * What should I do regarding the translation/localization, do I need to do it by myself?

The way we add a translation, we will add the same `<string name="...">` you have added to the default `strings.xml` to the `qq/strings.xml`, with a description of the string item.

>     * What about unit tests, I understand that some classes might be easier to test than others, is there a discussion for that? I want to add tests to my PR but some guidance would be nice!
> 

I do not think this PR would need a test case.

>     * Do we need a summary for this preference?

You can put this comment in the Phabacator ticket and tag our PM ( the one who created the ticket).

2025-01-04 01:34 UTC, cesonha commented
Thanks @cooltey , just did as you've said and commented in phabricator tagging them!

2025-01-11 20:46 UTC, cesonha commented
Hi @cooltey, it seems to be approved by the design and product team :) I've rebased with the main branch and added the string descriptions as you've said we should, should I just wait for code review/testing? :) TY

2025-01-13 21:18 UTC, cooltey requested changes

2025-01-13 21:18 UTC, cooltey commented on app/src/main/res/values-qq/strings.xml
> +  <string name="donor_history_deleted_message_snackbar">Success message shown briefly at the bottom of the screen after donation history has been deleted</string>
For the string items, I suggest using `donation_history` instead of `donor_history` to reduce confusion compared to the previous experimental feature.

2025-01-14 17:46 UTC, cesonha commented on app/src/main/java/org/wikipedia/settings/SettingsPreferenceLoader.kt
> +    private fun deleteLocalDonationHistory() {
agreed!

2025-01-14 17:47 UTC, cesonha commented on app/src/main/java/org/wikipedia/settings/SettingsPreferenceLoader.kt
> +        if (shouldShowDeleteLocalDonationHistoryPreference) {
makes sense ty

2025-01-15 17:22 UTC, cooltey approved these changes
All looks good! Thanks for the updates.

2025-01-15 17:54 UTC, merged